apiVersion: v1
kind: Service
metadata:
  name: mediassist-service
  namespace: mediassist
spec:
  selector:
    app: mediassist-app
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
  type: NodePort
