apiVersion: v1
kind: ConfigMap
metadata:
  name: mediassist-config
  namespace: mediassist
data:
  OLLAMA_BASE_URL: "http://host.minikube.internal:11434"
  CHROMA_DIR: "/app/chroma_store"
  OLLAMA_MODEL: "mistral"
  DATABASE_URL: "postgresql://mediassist:mediassist@postgres-service:5432/mediassist"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "60"
  MLFLOW_TRACKING_URI: "http://mlflow-service:5000"
